--- 
apiVersion: v1
kind: Pod
metadata: 
  name: mynginx
spec: 
  containers: 
    - 
      image: nginx
      name: nginx
      ports: 
        - 
          containerPort: 80
      volumeMounts: 
        - 
          mountPath: /var/log/nginx
          name: nginx-logs
    - 
      args: 
        - "-c"
        - "while true; do cat /dev/null > /logdir/access.log; sleep 10; done"
      command: 
        - /bin/sh
      image: busybox
      name: log-truncator
      volumeMounts: 
        - 
          mountPath: /logdir
          name: nginx-logs
#  nodeName: nodeb
  volumes: 
    - 
      emptyDir: {}
      name: nginx-logs

